version: '3.5'

services:
  # db:
    # container_name: company_viewer_db
    # image: postgres
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER:-admin}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
    #   POSTGRES_DB: ${POSTGRES_DB:-companies}
    #   PGDATA: /data/postgres
    # volumes:
    #    - postgres:/data/postgres
    # ports:
    #   - "5432:5432"
    # networks:
    #   - postgres
    # restart: unless-stopped
  
  web:
    container_name: company_viewer_web_app
    build:
      context: ../src/web/company-viewer-app
      dockerfile: Dockerfile
      args:
        API_URL: "${API_HOST}:${API_PORT}"
    ports:
      - "5665:80"
    restart: unless-stopped

# networks:
#   internal:
#     driver: bridge

# volumes:
#     postgres: